# Generated by Django 4.2.7 on 2024-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300, verbose_name='Sentence')),
                ('tense', models.CharField(choices=[('present_simple', 'Present Simple'), ('present_continuous', 'Present Continuous'), ('present_perfect', 'Present Perfect'), ('present_perfect_continuous', 'Present Perfect Continuous'), ('past_simple', 'Past Simple'), ('past_continuous', 'Past Continuous'), ('past_perfect', 'Past Perfect'), ('past_perfect_continuous', 'Past Perfect Continuous'), ('future_simple', 'Future Simple'), ('future_continuous', 'Future Continuous'), ('future_perfect', 'Future Perfect'), ('future_perfect_continuous', 'Future Perfect Continuous'), ('future_simple_in_the_past', 'Future Simple in the Past'), ('future_continuous_in_the_past', 'Future Continuous in the Past'), ('future_perfect_in_the_past', 'Future Perfect in the Past'), ('future_perfect_continuous_in_the_past', 'Future Perfect Continuous in the Past')], max_length=37, verbose_name='Tense')),
            ],
        ),
    ]
