# Generated by Django 4.2.7 on 2024-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='tense',
            field=models.CharField(choices=[('Pr Si', 'Present Simple'), ('Pr Co', 'Present Continuous'), ('Pr Pe', 'Present Perfect'), ('Pr Pe Co', 'Present Perfect Continuous'), ('Pa Si', 'Past Simple'), ('Pa Co', 'Past Continuous'), ('Pa Pe', 'Past Perfect'), ('Pa Pe Co', 'Past Perfect Continuous'), ('Fu Si', 'Future Simple'), ('Fu Co', 'Future Continuous'), ('Fu Pe', 'Future Perfect'), ('Fu Pe Co', 'Future Perfect Continuous')], max_length=37, verbose_name='Tense'),
        ),
    ]
